import type { Metadata } from "next";
import ClientLayout from "@/app/src/dashboard/dashlayout";
import "../app/src/dashboard/style.css";
import Provider from "./src/context/themeprovider";
import { EleveProvider } from "@/app/src/context/eleveContext";
import { ClasseProvider } from "@/app/src/context/classeContext";
import { MatiereProvider } from "@/app/src/context/matiereContext";
import { ProfesseurProvider } from "@/app/src/context/professeurContext"; // ✅ AJOUTE

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
    
  return (
    <html lang="en" suppressHydrationWarning>
      <body>
        <Provider>
          <EleveProvider>
            <ClasseProvider>
              <MatiereProvider>
                <ProfesseurProvider> {/* ✅ AJOUTE */}
                  <ClientLayout>{children}</ClientLayout>
                </ProfesseurProvider> {/* ✅ AJOUTE */}
              </MatiereProvider>
            </ClasseProvider>
          </EleveProvider>
        </Provider>
      </body>
    </html>
  );
}