
import type { Metadata } from "next";
//import { Geist, Geist_Mono } from "next/font/google";
//import Sidebar from "@/app/src/components/sidebar/sidebar";
//import Header from "@/app/src/components/headerP/header2";
import ClientLayout from "@/app/src/dashboard/dashlayout";
//import "./globals.css";
import "../app/src/dashboard/style.css";
import Provider from "./src/context/themeprovider";
//import { useState } from "react";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
    
  return (
    <html lang="en" suppressHydrationWarning>
      
      <body >
       
       <Provider>
          <ClientLayout>{children}</ClientLayout>
        </Provider>
        
      
      </body>
    </html>
  );
}
