import type { Metadata } from "next";
//import ClientLayout from "@/app/src/dashboard/dashlayout";
import "../app/src/dashboard/style.css";
import Provider from "./src/context/themeprovider";
import { EleveProvider } from "@/app/src/context/eleveContext";
import { ClasseProvider } from "@/app/src/context/classeContext";
import { MatiereProvider } from "@/app/src/context/matiereContext";
import { ProfesseurProvider } from "@/app/src/context/professeurContext";
import { SchoolProvider } from "@/app/src/context/schoolContext";
import { EvaluationFlashProvider } from "@/app/src/context/evaluationFlashContext"; // ✅ AJOUTE
import { UserProvider } from "@/app/src/context/userContext";
export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
    
  return (
    <html lang="en" suppressHydrationWarning>
      <body>
        <UserProvider>
          <Provider>
            <SchoolProvider>
              <EleveProvider>
                <ClasseProvider>
                  <MatiereProvider>
                    <ProfesseurProvider>
                      <EvaluationFlashProvider> 
                        {children}
                      </EvaluationFlashProvider> 
                    </ProfesseurProvider>
                  </MatiereProvider>
                </ClasseProvider>
              </EleveProvider>
            </SchoolProvider>
          </Provider>
        </UserProvider>
      </body>
    </html>
  );
}